/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as BecomeSupplierRouteImport } from './routes/become-supplier'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedCartRouteImport } from './routes/_authenticated/cart'
import { Route as AuthenticatedCheckoutRouteImport } from './routes/_authenticated/checkout'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedSupplierRouteRouteImport } from './routes/_authenticated/supplier/route'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as ProductsProductIdRouteImport } from './routes/products/$productId'
import { Route as SuppliersIndexRouteImport } from './routes/suppliers/index'
import { Route as SuppliersSupplierIdRouteImport } from './routes/suppliers/$supplierId'
import { Route as AuthenticatedOrdersIndexRouteImport } from './routes/_authenticated/orders/index'
import { Route as AuthenticatedSupplierIndexRouteImport } from './routes/_authenticated/supplier/index'
import { Route as AuthenticatedSupplierProfileRouteImport } from './routes/_authenticated/supplier/profile'
import { Route as AuthenticatedSupplierSubmissionsRouteImport } from './routes/_authenticated/supplier/submissions'
import { Route as AuthenticatedSupplierOrdersIndexRouteImport } from './routes/_authenticated/supplier/orders/index'
import { Route as AuthenticatedSupplierOrdersOrderIdRouteImport } from './routes/_authenticated/supplier/orders/$orderId'
import { Route as AuthenticatedSupplierProductsIndexRouteImport } from './routes/_authenticated/supplier/products/index'
import { Route as AuthenticatedSupplierProductsNewRouteImport } from './routes/_authenticated/supplier/products/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeSupplierRoute = BecomeSupplierRouteImport.update({
  id: '/become-supplier',
  path: '/become-supplier',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCartRoute = AuthenticatedCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCheckoutRoute = AuthenticatedCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupplierRouteRoute =
  AuthenticatedSupplierRouteRouteImport.update({
    id: '/supplier',
    path: '/supplier',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersIndexRoute = SuppliersIndexRouteImport.update({
  id: '/suppliers/',
  path: '/suppliers/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersSupplierIdRoute = SuppliersSupplierIdRouteImport.update({
  id: '/suppliers/$supplierId',
  path: '/suppliers/$supplierId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOrdersIndexRoute =
  AuthenticatedOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupplierIndexRoute =
  AuthenticatedSupplierIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSupplierRouteRoute,
  } as any)
const AuthenticatedSupplierProfileRoute =
  AuthenticatedSupplierProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedSupplierRouteRoute,
  } as any)
const AuthenticatedSupplierSubmissionsRoute =
  AuthenticatedSupplierSubmissionsRouteImport.update({
    id: '/submissions',
    path: '/submissions',
    getParentRoute: () => AuthenticatedSupplierRouteRoute,
  } as any)
const AuthenticatedSupplierOrdersIndexRoute =
  AuthenticatedSupplierOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => AuthenticatedSupplierRouteRoute,
  } as any)
const AuthenticatedSupplierOrdersOrderIdRoute =
  AuthenticatedSupplierOrdersOrderIdRouteImport.update({
    id: '/orders/$orderId',
    path: '/orders/$orderId',
    getParentRoute: () => AuthenticatedSupplierRouteRoute,
  } as any)
const AuthenticatedSupplierProductsIndexRoute =
  AuthenticatedSupplierProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AuthenticatedSupplierRouteRoute,
  } as any)
const AuthenticatedSupplierProductsNewRoute =
  AuthenticatedSupplierProductsNewRouteImport.update({
    id: '/products/new',
    path: '/products/new',
    getParentRoute: () => AuthenticatedSupplierRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/become-supplier': typeof BecomeSupplierRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/supplier': typeof AuthenticatedSupplierRouteRouteWithChildren
  '/account': typeof AuthenticatedAccountRoute
  '/cart': typeof AuthenticatedCartRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/suppliers/$supplierId': typeof SuppliersSupplierIdRoute
  '/products/': typeof ProductsIndexRoute
  '/suppliers/': typeof SuppliersIndexRoute
  '/supplier/profile': typeof AuthenticatedSupplierProfileRoute
  '/supplier/submissions': typeof AuthenticatedSupplierSubmissionsRoute
  '/orders/': typeof AuthenticatedOrdersIndexRoute
  '/supplier/': typeof AuthenticatedSupplierIndexRoute
  '/supplier/orders/$orderId': typeof AuthenticatedSupplierOrdersOrderIdRoute
  '/supplier/products/new': typeof AuthenticatedSupplierProductsNewRoute
  '/supplier/orders/': typeof AuthenticatedSupplierOrdersIndexRoute
  '/supplier/products/': typeof AuthenticatedSupplierProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/become-supplier': typeof BecomeSupplierRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/account': typeof AuthenticatedAccountRoute
  '/cart': typeof AuthenticatedCartRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/suppliers/$supplierId': typeof SuppliersSupplierIdRoute
  '/products': typeof ProductsIndexRoute
  '/suppliers': typeof SuppliersIndexRoute
  '/supplier/profile': typeof AuthenticatedSupplierProfileRoute
  '/supplier/submissions': typeof AuthenticatedSupplierSubmissionsRoute
  '/orders': typeof AuthenticatedOrdersIndexRoute
  '/supplier': typeof AuthenticatedSupplierIndexRoute
  '/supplier/orders/$orderId': typeof AuthenticatedSupplierOrdersOrderIdRoute
  '/supplier/products/new': typeof AuthenticatedSupplierProductsNewRoute
  '/supplier/orders': typeof AuthenticatedSupplierOrdersIndexRoute
  '/supplier/products': typeof AuthenticatedSupplierProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/become-supplier': typeof BecomeSupplierRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/supplier': typeof AuthenticatedSupplierRouteRouteWithChildren
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/cart': typeof AuthenticatedCartRoute
  '/_authenticated/checkout': typeof AuthenticatedCheckoutRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/suppliers/$supplierId': typeof SuppliersSupplierIdRoute
  '/products/': typeof ProductsIndexRoute
  '/suppliers/': typeof SuppliersIndexRoute
  '/_authenticated/supplier/profile': typeof AuthenticatedSupplierProfileRoute
  '/_authenticated/supplier/submissions': typeof AuthenticatedSupplierSubmissionsRoute
  '/_authenticated/orders/': typeof AuthenticatedOrdersIndexRoute
  '/_authenticated/supplier/': typeof AuthenticatedSupplierIndexRoute
  '/_authenticated/supplier/orders/$orderId': typeof AuthenticatedSupplierOrdersOrderIdRoute
  '/_authenticated/supplier/products/new': typeof AuthenticatedSupplierProductsNewRoute
  '/_authenticated/supplier/orders/': typeof AuthenticatedSupplierOrdersIndexRoute
  '/_authenticated/supplier/products/': typeof AuthenticatedSupplierProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/become-supplier'
    | '/login'
    | '/signup'
    | '/supplier'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/onboarding'
    | '/products/$productId'
    | '/suppliers/$supplierId'
    | '/products/'
    | '/suppliers/'
    | '/supplier/profile'
    | '/supplier/submissions'
    | '/orders/'
    | '/supplier/'
    | '/supplier/orders/$orderId'
    | '/supplier/products/new'
    | '/supplier/orders/'
    | '/supplier/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/become-supplier'
    | '/login'
    | '/signup'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/onboarding'
    | '/products/$productId'
    | '/suppliers/$supplierId'
    | '/products'
    | '/suppliers'
    | '/supplier/profile'
    | '/supplier/submissions'
    | '/orders'
    | '/supplier'
    | '/supplier/orders/$orderId'
    | '/supplier/products/new'
    | '/supplier/orders'
    | '/supplier/products'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/become-supplier'
    | '/login'
    | '/signup'
    | '/_authenticated/supplier'
    | '/_authenticated/account'
    | '/_authenticated/cart'
    | '/_authenticated/checkout'
    | '/_authenticated/onboarding'
    | '/products/$productId'
    | '/suppliers/$supplierId'
    | '/products/'
    | '/suppliers/'
    | '/_authenticated/supplier/profile'
    | '/_authenticated/supplier/submissions'
    | '/_authenticated/orders/'
    | '/_authenticated/supplier/'
    | '/_authenticated/supplier/orders/$orderId'
    | '/_authenticated/supplier/products/new'
    | '/_authenticated/supplier/orders/'
    | '/_authenticated/supplier/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  BecomeSupplierRoute: typeof BecomeSupplierRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  SuppliersSupplierIdRoute: typeof SuppliersSupplierIdRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  SuppliersIndexRoute: typeof SuppliersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-supplier': {
      id: '/become-supplier'
      path: '/become-supplier'
      fullPath: '/become-supplier'
      preLoaderRoute: typeof BecomeSupplierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cart': {
      id: '/_authenticated/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof AuthenticatedCartRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checkout': {
      id: '/_authenticated/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AuthenticatedCheckoutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supplier': {
      id: '/_authenticated/supplier'
      path: '/supplier'
      fullPath: '/supplier'
      preLoaderRoute: typeof AuthenticatedSupplierRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers/': {
      id: '/suppliers/'
      path: '/suppliers'
      fullPath: '/suppliers/'
      preLoaderRoute: typeof SuppliersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers/$supplierId': {
      id: '/suppliers/$supplierId'
      path: '/suppliers/$supplierId'
      fullPath: '/suppliers/$supplierId'
      preLoaderRoute: typeof SuppliersSupplierIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/orders/': {
      id: '/_authenticated/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AuthenticatedOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supplier/': {
      id: '/_authenticated/supplier/'
      path: '/'
      fullPath: '/supplier/'
      preLoaderRoute: typeof AuthenticatedSupplierIndexRouteImport
      parentRoute: typeof AuthenticatedSupplierRouteRoute
    }
    '/_authenticated/supplier/profile': {
      id: '/_authenticated/supplier/profile'
      path: '/profile'
      fullPath: '/supplier/profile'
      preLoaderRoute: typeof AuthenticatedSupplierProfileRouteImport
      parentRoute: typeof AuthenticatedSupplierRouteRoute
    }
    '/_authenticated/supplier/submissions': {
      id: '/_authenticated/supplier/submissions'
      path: '/submissions'
      fullPath: '/supplier/submissions'
      preLoaderRoute: typeof AuthenticatedSupplierSubmissionsRouteImport
      parentRoute: typeof AuthenticatedSupplierRouteRoute
    }
    '/_authenticated/supplier/orders/': {
      id: '/_authenticated/supplier/orders/'
      path: '/orders'
      fullPath: '/supplier/orders/'
      preLoaderRoute: typeof AuthenticatedSupplierOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedSupplierRouteRoute
    }
    '/_authenticated/supplier/orders/$orderId': {
      id: '/_authenticated/supplier/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/supplier/orders/$orderId'
      preLoaderRoute: typeof AuthenticatedSupplierOrdersOrderIdRouteImport
      parentRoute: typeof AuthenticatedSupplierRouteRoute
    }
    '/_authenticated/supplier/products/': {
      id: '/_authenticated/supplier/products/'
      path: '/products'
      fullPath: '/supplier/products/'
      preLoaderRoute: typeof AuthenticatedSupplierProductsIndexRouteImport
      parentRoute: typeof AuthenticatedSupplierRouteRoute
    }
    '/_authenticated/supplier/products/new': {
      id: '/_authenticated/supplier/products/new'
      path: '/products/new'
      fullPath: '/supplier/products/new'
      preLoaderRoute: typeof AuthenticatedSupplierProductsNewRouteImport
      parentRoute: typeof AuthenticatedSupplierRouteRoute
    }
  }
}

interface AuthenticatedSupplierRouteRouteChildren {
  AuthenticatedSupplierProfileRoute: typeof AuthenticatedSupplierProfileRoute
  AuthenticatedSupplierSubmissionsRoute: typeof AuthenticatedSupplierSubmissionsRoute
  AuthenticatedSupplierIndexRoute: typeof AuthenticatedSupplierIndexRoute
  AuthenticatedSupplierOrdersOrderIdRoute: typeof AuthenticatedSupplierOrdersOrderIdRoute
  AuthenticatedSupplierProductsNewRoute: typeof AuthenticatedSupplierProductsNewRoute
  AuthenticatedSupplierOrdersIndexRoute: typeof AuthenticatedSupplierOrdersIndexRoute
  AuthenticatedSupplierProductsIndexRoute: typeof AuthenticatedSupplierProductsIndexRoute
}

const AuthenticatedSupplierRouteRouteChildren: AuthenticatedSupplierRouteRouteChildren =
  {
    AuthenticatedSupplierProfileRoute: AuthenticatedSupplierProfileRoute,
    AuthenticatedSupplierSubmissionsRoute:
      AuthenticatedSupplierSubmissionsRoute,
    AuthenticatedSupplierIndexRoute: AuthenticatedSupplierIndexRoute,
    AuthenticatedSupplierOrdersOrderIdRoute:
      AuthenticatedSupplierOrdersOrderIdRoute,
    AuthenticatedSupplierProductsNewRoute:
      AuthenticatedSupplierProductsNewRoute,
    AuthenticatedSupplierOrdersIndexRoute:
      AuthenticatedSupplierOrdersIndexRoute,
    AuthenticatedSupplierProductsIndexRoute:
      AuthenticatedSupplierProductsIndexRoute,
  }

const AuthenticatedSupplierRouteRouteWithChildren =
  AuthenticatedSupplierRouteRoute._addFileChildren(
    AuthenticatedSupplierRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSupplierRouteRoute: typeof AuthenticatedSupplierRouteRouteWithChildren
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedCartRoute: typeof AuthenticatedCartRoute
  AuthenticatedCheckoutRoute: typeof AuthenticatedCheckoutRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedOrdersIndexRoute: typeof AuthenticatedOrdersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSupplierRouteRoute: AuthenticatedSupplierRouteRouteWithChildren,
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedCartRoute: AuthenticatedCartRoute,
  AuthenticatedCheckoutRoute: AuthenticatedCheckoutRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedOrdersIndexRoute: AuthenticatedOrdersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  BecomeSupplierRoute: BecomeSupplierRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
  SuppliersSupplierIdRoute: SuppliersSupplierIdRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  SuppliersIndexRoute: SuppliersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
